version: "3"

services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                     C O D E I G N I T E R  v4.0.4                        #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
    codeigniter4:
        image: ci4-image
        container_name: 'ci4'
        ports:
          - 80:80
        links:
          - ci4_mariadb
        volumes:
          - /var/www/html:/var/www/html                  
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                               M Y S Q L                                  #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#               
    ci4_mariadb:
        image: mariadb:10.5.5
        container_name: 'ci4_mariadb'
        ports:
          - 3306:3306
        volumes:
          - /docker/volumes/databases/mysql:/var/lib/mysql
          - /docker/volumes/databases/logs/mysql:/var/log/mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: codeigniter4
          MYSQL_USER: codeigniter4
          MYSQL_PASSWORD: codeigniter4

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                         P H P M Y A D M I N                              #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#             
    codeigniter4_phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.2
        container_name: 'ci4_phpmyadmin'
        links:
          - ci4_mariadb
        environment:
          PMA_HOST: ci4_mariadb
          PMA_PORT: 3306
        ports:
          - 81:80
        volumes:
          - /docker/volumes/databases/sessions:/sessions
